

CREATE DATABASE Exercicio_1_3

USE Exercicio_1_3

--PRIMARY KEY
CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(20) NOT NULL
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL,
	Nome VARCHAR(20) NOT NULL,
	Expediente VARCHAR(20) NOT NULL
);

--PRIMARY KEY
CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	TipoPet VARCHAR(20) NOT NULL
);

--PRIMARY KEY
CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Raca VARCHAR(20) NOT NULL
);

CREATE TABLE Pets
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca) NOT NULL,
	Nome VARCHAR(20) NOT NULL,
	DataNascimento VARCHAR(20) NOT NULL,
	Cliente VARCHAR(20) NOT NULL,
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario) NOT NULL,
	IdPet INT FOREIGN KEY REFERENCES Pets(IdPet) NOT NULL
);



