-- DDL 

-- CRIAR BD

CREATE DATABASE Exercicio_1_2

--USAR O BD

USE Exercicio_1_2

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(15) NOT NULL
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Modelo VARCHAR(15) NOT NULL
);

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Marca VARCHAR(15) NOT NULL
);

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	Placa VARCHAR(7) UNIQUE NOT NULL
);

CREATE TABLE Cliente 
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL
);

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Valor VARCHAR(10) NOT NULL,
	DataInicio VARCHAR(10) NOT NULL,
	DataFim VARCHAR(10) NOT NULL
);

select

* 
from 
Cliente,
Empresa,
,
Marca
DROP TABLE Aluguel